# 針對 study2 資料集少於 5 者要去該 class

In [76]:
import pandas as pd
df = pd.read_csv('/Users/emily/Desktop/oh15.wc.csv')
# dfclean = df.dropna().reset_index(drop=True)
df.dropna(axis=1)

/Users/emily/Desktop/Research/oversampling_python/venv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3437: DtypeWarning: Columns (105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,cluster,infus,gland,dopamin,phagocytosi,fetal,signific,penetr,hepat,cigarett,fusion,nitroprussid,rifampin
0,{36 3,204 1,275 9,373 4,382 1,502 1,512 1,526 1,532 1,567 1,578 1,739 1,746 1
1,{125 2,146 1,206 1,228 2,256 1,314 2,325 2,373 1,424 3,486 2,517 3,556 1,601 2
2,{61 1,112 1,183 1,257 1,373 2,424 1,493 4,839 1,1142 1,1166 1,1269 1,1483 1,1777 2
3,{6 1,69 2,90 1,215 1,216 2,280 1,355 1,366 5,373 6,598 1,612 1,805 1,848 2
4,{69 3,141 1,168 1,243 1,294 3,302 9,351 1,373 6,378 1,398 10,423 1,441 1,469 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
908,{22 4,90 1,108 1,358 11,363 1,373 2,382 2,493 1,507 1,539 1,577 1,612 1,633 1
909,{21 2,22 6,47 1,52 1,64 3,129 1,203 2,273 1,313 1,343 1,382 3,396 2,456 1
910,{61 1,77 1,141 1,224 1,239 3,247 7,258 3,314 2,336 2,339 1,358 3,493 1,556 2
911,{209 1,315 1,373 1,461 2,583 1,851 2,997 1,1047 1,1139 1,1197 1,1227 1,1245 1,1287 1
912,{112 1,126 1,180 2,209 1,218 1,269 1,359 1,373 6,382 1,398 6,493 1,512 5,577 1

In [74]:
df.notna()

,cluster,infus,gland,dopamin,phagocytosi,fetal,signific,penetr,hepat,cigarett,...,angiopathi,fix,western,innerv,able,congenit,essenti,inner,multivari,CLASS_LABEL
0,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
4,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
908,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
909,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
910,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
911,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
912,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False

In [58]:
dfclean

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,75,0,190,80,91,193,371,174,121,-16,...,0.0,9.0,-0.9,0.0,0.0,0.9,2.9,23.3,49.4,8
1,56,1,165,64,81,174,401,149,39,25,...,0.0,8.5,0.0,0.0,0.0,0.2,2.1,20.4,38.8,6
2,54,0,172,95,138,163,386,185,102,96,...,0.0,9.5,-2.4,0.0,0.0,0.3,3.4,12.3,49.0,10
3,55,0,175,94,100,202,380,179,143,28,...,0.0,12.2,-2.2,0.0,0.0,0.4,2.6,34.6,61.6,1
4,75,0,190,80,88,181,360,177,103,-16,...,0.0,13.1,-3.6,0.0,0.0,-0.1,3.9,25.4,62.8,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,53,1,160,70,80,199,382,154,117,-37,...,0.0,4.3,-5.0,0.0,0.0,0.7,0.6,-4.4,-0.5,1
448,37,0,190,85,100,137,361,201,73,86,...,0.0,15.6,-1.6,0.0,0.0,0.4,2.4,38.0,62.4,10
449,36,0,166,68,108,176,365,194,116,-85,...,0.0,16.3,-28.6,0.0,0.0,1.5,1.0,-44.2,-33.2,2
450,32,1,155,55,93,106,386,218,63,54,...,-0.4,12.0,-0.7,0.0,0.0,0.5,2.4,25.0,46.6,1
451,78,1,160,70,79,127,364,138,78,28,...,0.0,10.4,-1.8,0.0,0.0,0.5,1.6,21.3,32.8,1

In [59]:
Counter(dfclean.iloc[:,-1])

Counter({8: 2,
         6: 25,
         10: 50,
         1: 245,
         7: 3,
         14: 4,
         3: 15,
         16: 22,
         2: 44,
         4: 15,
         5: 13,
         9: 9,
         15: 5})

In [67]:
from collections import Counter
c = Counter(dfclean.iloc[:,-1])
cd = dict(c)
lastcolumn = df.columns[-1]
# print(lastcolumn)

dfcleandrop = dfclean 
for key,count in cd.items():
    if count < 5 :
        print(key)
        dfcleandropclass = dfcleandrop[dfcleandrop[lastcolumn] != key ]
        dfcleandrop = dfcleandropclass
Counter(dfcleandrop.iloc[:,-1])
dfcleandrop.to_csv('/Users/emily/Desktop/arrhythmiadrop.csv')

8
7
14

In [37]:
dfcleandrop = dfclean[dfclean['Classes'] != 'class3']
dfcleandrop = dfcleandrop[dfcleandrop['Classes'] != 'class1' ]
dfcleandrop = dfcleandrop[dfcleandrop['Classes'] != 'class5' ]
Counter(dfcleandrop.iloc[:,-1])
dfcleandrop.to_csv('/Users/emily/Desktop/SCADI-Dataset/SCADI-dropdata.csv')

7
8
14
8
8
8

In [3]:
df.dropna()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71
3,Subject,Hold .,Hold t,Hold i,Hold e,Hold Shift,Hold 5,Hold Shift,Hold Caps,Hold r,...,Size Caps,Size r,Size o,Size a,Size n,Size l,Size Enter,AvH,AvP,AvA
4,1,89,92,64,85,123,82,70,101,84,...,0.225806,0.225806,0.322581,0.290323,0.225806,0.354839,0.258065,88.071429,0.190971,0.288018
5,1,90,88,99,83,123,101,81,94,88,...,0.225806,0.225806,0.322581,0.322581,0.258065,0.387097,0.322581,92.071429,0.186514,0.274194
6,1,87,90,83,65,79,73,96,62,64,...,0.225806,0.193548,0.290323,0.322581,0.225806,0.258065,0.225806,83.571429,0.186171,0.271889
7,1,71,81,62,72,83,94,89,104,73,...,0.225806,0.225806,0.258065,0.290323,0.225806,0.322581,0.322581,81.428571,0.177943,0.278802
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2910,56,79,73,89,72,52,78,67,77,71,...,0.129032,0.225806,0.193548,0.129032,0.129032,0.258065,0.225806,77.714286,0.092229,0.184332
2911,56,65,98,73,75,62,67,85,68,64,...,0.258065,0.225806,0.225806,0.16129,0.225806,0.16129,0.290323,75.142857,0.133714,0.235023
2912,56,88,85,71,63,104,81,85,80,82,...,0.225806,0.258065,0.290323,0.322581,0.322581,0.225806,0.258065,77.214286,0.1536,0.267281
2913,56,99,98,80,95,71,76,70,78,54,...,0.225806,0.225806,0.258065,0.225806,0.193548,0.225806,0.354839,74.714286,0.111429,0.258065
2914,56,80,73,97,94,61,65,96,70,54,...,0.225806,0.225806,0.290323,0.258065,0.193548,0.322581,0.322581,71.857143,0.114514,0.260369